# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SimMixC <- function(N, mu, sigma, p) {
    .Call(`_SimpleSim_SimMixC`, N, mu, sigma, p)
}

